Insta/urls.py
from django.urls import path

from Insta.views import (EditProfile, ExploreView, PostCreateView,
                         PostDeleteView, PostDetailView, PostListView,
                         PostUpdateView, SignUp, UserProfile, addComment,
                         addLike, toggleFollow, FollowersView, FollowingsView)

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post'),
    path('post/new/', PostCreateView.as_view(), name='make_post'),
    path('post/edit/<int:pk>', PostUpdateView.as_view(), name='edit_post'),
    path('post/delete/<int:pk>', PostDeleteView.as_view(), name='delete_post'),
    path('auth/signup', SignUp.as_view(), name='signup'),
    path('user_profile/<int:pk>/', UserProfile.as_view(), name='profile'),
    path('edit_profile/<int:pk>/', EditProfile.as_view(), name='edit_profile'),
    path('togglefollow', toggleFollow, name='togglefollow'),
    path('like', addLike, name='addLike'),
    path('comment', addComment, name='addComment'),
    path('explore', ExploreView.as_view(), name='explore'),
    path('followers/<int:pk>', FollowersView.as_view(), name = 'followers'),
    path('followings/<int:pk>', FollowingsView.as_view(), name = 'followings'),
]

InstaDemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Insta.urls')),
    path('auth/', include('django.contrib.auth.urls'))
]

Insta/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from imagekit.models import ProcessedImageField

# Create your models here.

class InstaUser(AbstractUser):
    profile_pic = ProcessedImageField(
        upload_to='static/images/profiles',
        format='JPEG',
        options={'quality': 100},
        null=True,
        blank=True,
        )

    def get_connections(self):
        connections = UserConnection.objects.filter(creator=self)
        return connections

    def get_followers(self):
        followers = UserConnection.objects.filter(following=self)
        return followers

    def is_followed_by(self, user):
        followers = UserConnection.objects.filter(following=self)
        return followers.filter(creator=user).exists()

    def get_absolute_url(self):
        return reverse('profile', args=[str(self.id)])

    def __str__(self):
        return self.username


class UserConnection(models.Model):
    created = models.DateTimeField(auto_now_add=True, editable=False)
    creator = models.ForeignKey(
        InstaUser,
        on_delete=models.CASCADE,
        related_name="friendship_creator_set")
    following = models.ForeignKey(
        InstaUser,
        on_delete=models.CASCADE,
        related_name="friend_set")

    def __str__(self):
        return self.creator.username + ' follows ' + self.following.username

class Post(models.Model):
    author = models.ForeignKey( # a foreign key indicate a Many-To-One relationship
        InstaUser, #foreign key is InstaUser
        blank=True,
        null=True,
        on_delete=models.CASCADE, # delete this author will delete all his posts
        related_name='posts', # we can use author.posts to get all posts belong to this user
        )
    title = models.TextField(blank=True, null=True)
    image = ProcessedImageField(
        upload_to='static/images/posts',
        format='JPEG',
        options={'quality': 100},
        blank=True,
        null=True,
        )
    posted_on = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post", args=[str(self.id)])

    def get_like_count(self):
        return self.likes.count()

    def get_comment_count(self):
        return self.comments.count()

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments',)
    user = models.ForeignKey(InstaUser, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    posted_on = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return self.comment

class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes',)
    user = models.ForeignKey(InstaUser, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("post", "user")

    def __str__(self):
        return 'Like: ' + self.user.username + ' ' + self.post.title

templates/base.html
<html>
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>JZ Insta</title>
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'vendor/font-awesome-4.6.3/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    </head>
    <body>

        {% load static %}
        {% include 'header.html' %}
        
        <div class="content-wrapper">
            <div class="container">
                {% block content %}
                {% endblock content%}
            </div>
        </div>

        <script type="text/javascript" src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/ajax-csrf-auth.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/index.js' %}"></script>

        {% block extrascript %}
        {% endblock %}

    </body>
</html>
    

templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}

<div class="row profile-settings">
  <div class="col-xs-12">
    <div class="profile-pic-name">
      {% if user.profile_pic %}
        <img class="picture-circle--medium" src="http://{{ request.META.HTTP_HOST }}/{{user.profile_pic.url}}">
      {% endif %}
      <span class="username">{{ user.username }}</span>
    </div>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update" />
    </form>
  </div>
</div>

{% endblock content %}

templates/explore.html
{% extends "base.html" %}

{% block content %}

<div class="row" id="explore">
  {% for post in object_list %}
    <div class="col-xs-4 col-sm-3">
      <div class="picture-square" style="background-image: url(http://{{ request.META.HTTP_HOST }}/{{ post.image.url }}); background-size: contain;">
        <a href="{% url 'post' post.pk %}">
          <div class="content"></div>
        </a>
      </div>
    </div>
  {% endfor %}
</div>


{% endblock %}

templates/followers.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<div class="cards-listing">
    {% for user in object_list %}
        <div class="row">
            <div class="card view-update {{ user.pk }}">
                <div class="card__panel-head">
                    <div class="poster__info">
                        <a href="{% url 'profile' user.id %}" class="poster__name">
                            {% if user.profile_pic %}
                                <img class="poster__profilepic" src="/{{ user.profile_pic.url }}">
                            {% endif %}
                            {{ user.username }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

templates/followings.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<div class="cards-listing">
    {% for object in object_list %}
        <div class="row">
            <div class="card view-update {{ object.pk }}">
                <div class="card__panel-head">
                    <div class="poster__info">
                        <a href="{% url 'profile' object.id %}" class="poster__name">
                            {% if user.profile_pic %}
                                <img class="poster__profilepic" src="/{{ object.profile_pic.url }}">
                            {% endif %}
                            {{ object.username }}
                        </a>
                    </div>
                    {% comment %} {% is_following user object as following %}
                    <div class="follow-toggle__container">
                        <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}" id="{{ object.pk }}">
                            {% if following %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>
                    </div> {% endcomment %}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

templates/header.html
{% load custom_tags %}

<div class="navbar navbar-default navbar-fixed-top" id="main-nav">
    <div class="container desktop">
        <div class="navbar-header">
            <a href="/" class="navbar-brand">Jiuzhang Insta</a>
        </div>

        <div id="navbar-main">
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li>
                      <a href="{% url 'home' %}">
                        <i class="fa fa-home {% if request.resolver_match.url_name == 'home' %}active{% endif %}" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li><a href="{% url 'explore' %}"><i class="fa fa-search {% active 'explore' %}" aria-hidden="true"></i></a></li>
                    <li><a href="{% url 'make_post' %}"><i class="fa fa-plus {% active 'make_post' %}" aria-hidden="true"></i></a></li>
                    <li><a href="{% url 'profile' request.user.pk %}"><i class="fa fa-user {% active 'profile' %}" aria-hidden="true"></i></a></li>
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out {% active 'logout' %}" aria-hidden="true"></i></a></li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">login</a>
                    </li>
                    <li>
                        <a href="{% url 'signup' %}">signup</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>

templates/home.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<div class="cards-listing">
    {% for post in object_list %}
        <div class="row">
            <div class="card view-update {{ post.pk }}">
                <div class="card__panel-head">
                    <div class="poster__info">
                        <a href="{% url 'profile' post.author.pk %}" class="poster__name">
                            {% if post.author.profile_pic %}
                                <img class="poster__profilepic" src="{{ post.author.profile_pic.url }}">
                            {% endif %}
                            {{ post.author.username }}
                        </a>
                        <span class="poster__timestamp">
                            {{ post.posted_on|timesince }}
                        </span>
                    </div>
                </div>
                <a href="{% url 'post' post.pk %}">
                    <img class="card__main-image" src="{{ post.image.url }}">
                </a>
                <div class="card__panel-body">
                    <div class="likes">
                        {% if post.get_like_count %}
                            {{ post.get_like_count }} like{% if post.get_like_count > 1 %}s{% endif %}
                        {% endif %}
                    </div>
                    <ul class="comment-list">
                        <a class="view-more"></a>
                        {% for comment in post.comments.all %}
                        <li class="comment-list__comment">
                            <a href="{% url 'profile' comment.user.pk %}" class="user">
                                {{ comment.user.username }}
                            </a>
                            <span class="comment">{{ comment.comment }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <section class="input-row">
                        <i class="fa {% has_user_liked_post post user %} submit-like" aria-hidden="true"></i>
                        <div class="comment-input-wrapper">
                            <input class="add-comment" type="text" placeholder="Add a comment...">
                        </div>
                        <div class="hidden-data {{ post.pk }}" style="display: none;">
                            <span class="post-pk">{{ post.pk }}</span>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock content %}

templates/make_post.html
{% extends "base.html" %}

{% block content %}

<h1>New Post</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>
        <label for="id_title">Title:</label>
        <textarea name="title" cols="40" rows="10" id="id_title">
        </textarea>
    </p>
    <p>
        <label for="id_image">Image:</label>
        <input type="file" name="image" accept="image/*" id="id_image">
    </p>
    <button type="submit">Save</button>
</form>

{% endblock content %}

templates/post_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Delete Post</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{post.title}}" ? </p>
    <button type="submit">Confirm delete</button>
</form>

{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}

{% load custom_tags %}

{% block content %}

<div class="row single-post">
    <div class="single-post-card view-update {{ object.pk }}">
        <div class="header">
            <a href="{% url 'profile' object.author.pk %}">
                {% if object.author.profile_pic %}
                    <img class="picture-circle--medium" src="http://{{ request.META.HTTP_HOST }}/{{object.author.profile_pic.url}}">
                {% endif %}
                {{ object.author.username }}
            </a>
        </div>
        <div class="image__wrapper">
            <img class="card__main-image" src="http://{{ request.META.HTTP_HOST }}/{{object.image.url}}" width='1000', height='1000'>
        </div>
        <div class="comments-portion">
            <div class="likes-timestamp-row">
                <div class="likes">
                    {% if object.get_like_count %}
                        {{ object.get_like_count }} like{% if object.get_like_count > 1 %}s{% endif %}
                    {% endif %}
                </div>
                <div class="timestamp">
                    {{ object.posted_on|timesince }}
                </div>
            </div>
            <ul class="comment-list">
                {% for comment in object.comments.all %}
                <li class="comment-list__comment">
                    <a href="{% url 'profile' comment.user.pk %}" class="user">
                        {{ comment.user.username }}
                    </a>
                    <span class="comment">{{ comment.comment }}</span>
                </li>
                {% endfor %}
            </ul>
            <section class="input-row">
                <i class="fa {% if liked %}fa-heart{% else %}fa-heart-o{% endif %} submit-like" aria-hidden="true"></i>
                <div class="comment-input-wrapper">
                    <input class="add-comment" type="text" placeholder="Add a comment...">
                </div>
                <div class="hidden-data {{ object.pk }}" style="display: none;">
                    <span class="post-pk">{{ object.pk }}</span>
                </div>
            </section>
        </div>
    </div>
</div>

{% endblock content %}

templates/post_edit.html
{% extends "base.html" %}

{% block content %}

<h1>Edit Post</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>

{% endblock content %}

templates/signup.html
{% extends "base.html" %}

{% block content %}

<h2>Sign up</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>

{% endblock content %}

templates/user_profile.html
{% extends 'base.html' %}

{% load custom_tags %}

{% block content %}

<div class="profile">

    <div class="profile__head">
        <div class="row">
            <div class="col-xs-4 left">
                {% if object.profile_pic %}
                    <img class="picture-circle" src="http://{{ request.META.HTTP_HOST }}/{{object.profile_pic.url}}">
                {% endif %}
            </div>
            <div class="col-xs-8 right">
                <div class="name-buttons">
                    <h1 class="username">{{ object.username }}</h1>
                    {% if user == object %}
                        <a class="edit-desktop" href="{% url 'edit_profile' object.pk %}">
                            <button class="edit-profile">Edit Profile</button>
                        </a>
                    {% else %}
                        {% is_following user object as following %}
                        <div class="follow-toggle__container">
                            <button class="btn btn-primary {% if not following %}follow-user{% else %}unfollow-user{% endif %}" id="{{ object.pk }}">
                                {% if following %}
                                    Unfollow
                                {% else %}
                                    Follow
                                {% endif %}
                            </button>
                        </div>
                    {% endif %}
                </div>

                <div>
                    <ul class="stats">
                        <div class="col-xs-4"><li class="stats__count"><span>{{ object.posts.count }}</span><br> posts</li></div>
                        <div class="col-xs-4"><a href="{% url 'followers' object.id %}" style="text-decoration: none; color: black;"><li class="stats__count"><span class="follower_count" id="follower_id">{{ object.get_followers.count }}</span><br> followers</li></a></div>
                        <div class="col-xs-4"><a href="{% url 'followings' object.id %}" style="text-decoration: none; color: black;"><li class="stats__count"><span>{{ object.get_connections.count }}</span><br> following</li></a></div>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="profile__body">
        <div class="row">
        {% for post in object.posts.all %}
            <div class="col-xs-4">
                <div class="picture-square" style="background-image: url(http://{{ request.META.HTTP_HOST }}/{{ post.image.url }}); background-size: contain;">
                    <a href="{% url 'post' post.pk %}">
                    <div class="content">
                        <i class="fa fa-heart" aria-hidden="true"></i> {{ post.get_like_count }}
                        <i class="fa fa-comment" aria-hidden="true"></i> {{ post.get_comment_count }}
                    </div>
                    </a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>

</div>

{% endblock content %}